name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build win-x64
      run: dotnet publish QbtManager.sln -c Release --runtime win-x64 --self-contained -o artifacts/QbtManager-win /p:PublishSingleFile=true /p:AssemblyVersion=1.0.${{ github.run_number }}
      
    - name: Build linux-x64
      run: dotnet publish QbtManager.sln -c Release --runtime linux-x64 --self-contained -o artifacts/QbtManager-linux /p:PublishSingleFile=true /p:AssemblyVersion=1.0.${{ github.run_number }}
      
    - name: Build osx-x64
      run: dotnet publish QbtManager.sln -c Release --runtime osx-x64 --self-contained -o artifacts/QbtManager-osx /p:PublishSingleFile=true /p:AssemblyVersion=1.0.${{ github.run_number }}
    
    - name: Zip the Win release
      run: zip ./artifacts/QbtManager-win.zip ./artifacts/QbtManager-win/QbtManager.exe

    - name: Zip the OSX release
      run: zip ./artifacts/QbtManager-osx.zip ./artifacts/QbtManager-osx/QbtManager

    - name: Zip the Linux release
      run: zip ./artifacts/QbtManager-linux.zip ./artifacts/QbtManager-linux/QbtManager
      
    - name: Upload win to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QbtManager-win.zip
        path: ./artifacts/QbtManager-win.zip
    - name: Upload mac to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QbtManager-osx.zip
        path: ./artifacts/QbtManager-osx.zip
    - name: Upload linux to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QbtManager-linux.zip
        path: ./artifacts/QbtManager-linux.zip
        
    - name: Upload win binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifacts/QbtManager-win.zip
        tag: ${{ github.ref }}
        file_glob: true
        
    - name: Upload macos binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifacts/QbtManager-osx.zip
        tag: ${{ github.ref }}
        file_glob: true
        
    - name: Upload linux binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifacts/QbtManager-linux.zip
        tag: ${{ github.ref }}
        file_glob: true

